### ISSUE TITLE
Add support for Sitemap plugin

### ISSUE THREAD

**Issue by RomainMazB** [wintercms/wn-forum-plugin#6]
This plugin should register a custom item types to the Page plugin to be able to add to the Sitemap plugin at least all channels urls and all topics urls.

Currently toying with it to build a tiny forum, I'll probably make a PR soon, if any suggestion on what should be or not.

**Comment by LukeTowers** [comment]
I'm not opposed to having it list the topics, it is after all an optional item that can be added or not added to the sitemap's definition by the developer, it could even be part of it's own separate definition that's submitted to search engines separately from the main one.

**Comment by bennothommo** [comment]
Sitemap support for the Forum plugin has been implemented by https://github.com/wintercms/wn-forum-plugin/pull/9.
